### ISSUE TITLE
Summary values have incorrect format

### ISSUE THREAD

**Issue by BoredMind** [gwendo/entities-table-card#6]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
v0.0.4

**Browser and Operating System:**
Chrome/Firefox Windows, Android, Mac

**Description of problem:**
showSummary doesn't appear to be following column format.  No matter what the format is set for the column, the summary is always an unformatted number.   

Example:

  - header: '%'
    attr: changePercent
    format: percentage
    showSummary: true

The values in the column before the summary are formatted as % but the summary comes across as currency maybe?  I cannot tell. 

  - header: Value
    attr: totalValue
    format: currency
    showSummary: true

The values in the column as currency with a comma between thousands in the values, but the summary is just a straight number with no formatting at all.

**Comment by gwendo** [comment]
I agree with the currency value being formatted incorrectly, when it comes to summarizing percentage values I'm not sure how it would work correctly as just summarizing individual percentage values would most likely show an incorrect value for the entire card
